### ISSUE TITLE
AntiRaid as Captcha

### ISSUE THREAD

**Issue by samuele794** [Coding-Bunker/CodingBunker-Expanse-Discord-Bot#1]
Questa funzionalità sarà gestita in locale dal bot.

L'obiettivo di questa funzione è il verificare che chi entra dentro al server sia un essere umano.

Sul server ci sarà un canale visibile solamente ai non verificati.

Nota: ai non verificati non verrà assegnato nessun ruolo e il canale è visibile solo a chi non ha nessun ruolo

All'ingresso nel server il bot invierà un immagine simil reCaptcha, da risolvere entro 10 minuti.

Il reCaptcha sarà resettabile tramite apposito comando da inviare in privato.

Dopo la risoluzione corretta verrà rimosso il ruolo temporaneo e passato al permesso "Junior Member".

Dopo 1 ora dall'ingresso nel server l'utente verrà kickato dal server con un messaggio privato di avviso e il link di invito.

**Update 11/05/2021:**

In caso l'utente abbia i messaggi privati disabilitati, dovrà essere inviato un messaggio su un canale dedicato allo staff:
<Tag dello STAF/Mod e così via> <nickname#discriminatore> <idUtente>

**Comment by fabryscript** [comment]
Ho trovato [questo bot interessante](https://discordcaptcha.xyz/commands.php), che magari dopo averci prodotto il risultato possiamo tranquillamente fare l'handling vario dei ruoli, che ne pensi?

**Comment by samuele794** [comment]
nope, l'obbiettivo di base sarebbe quello di sganciarci da bot esterni completamente (salvo casi rari e vagliati caso per caso)

**Comment by fabryscript** [comment]
Ah nice, quindi bisognerebbe fare il sistema di captcha da zero? 😳

**Comment by Giuliopime** [comment]
No beh, ma quelli li prenderemo da qualche API

**Comment by fabryscript** [comment]
Aaaah eccooo

**Comment by samuele794** [comment]
Ovviamente le librerie sono ammesse per generare l'immagine.

> Nota: ai non verificati non verrà assegnato nessun ruolo e il canale è visibile solo a chi non ha nessun ruolo

per questa nota ovviamente c'è da fare una leggera sperimentazione

**Comment by fabryscript** [comment]
Ho capito, va bien!

**Comment by samuele794** [comment]
Update 11/05/2021

**Comment by fabryscript** [comment]
Update: Credo manchi solo il fatto di disturbare l'immagine e del resto abbiamo concluso la feature.

**Comment by samuele794** [comment]
> Update: Credo manchi solo il fatto di disturbare l'immagine e del resto abbiamo concluso la feature.

Yep, ma anche provare e documentare i permessi per i canali da configurare
